
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANNEGILLIAN
 */
public class RADIOBTN extends javax.swing.JFrame {

    /**
     * Creates new form RADIOBTN
     */
    public RADIOBTN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        RADIOBTNbird = new javax.swing.JRadioButton();
        RADIOBTNcat = new javax.swing.JRadioButton();
        RADIOBTNdog = new javax.swing.JRadioButton();
        RADIOBTNrabbit = new javax.swing.JRadioButton();
        RADIOBTNpig = new javax.swing.JRadioButton();
        RADIOBTNTITLE = new javax.swing.JLabel();
        picdisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(RADIOBTNbird);
        RADIOBTNbird.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RADIOBTNbird.setText("BIRD");
        RADIOBTNbird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RADIOBTNbirdActionPerformed(evt);
            }
        });

        buttonGroup1.add(RADIOBTNcat);
        RADIOBTNcat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RADIOBTNcat.setText("CAT");
        RADIOBTNcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RADIOBTNcatActionPerformed(evt);
            }
        });

        buttonGroup1.add(RADIOBTNdog);
        RADIOBTNdog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RADIOBTNdog.setText("DOG");
        RADIOBTNdog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RADIOBTNdogActionPerformed(evt);
            }
        });

        buttonGroup1.add(RADIOBTNrabbit);
        RADIOBTNrabbit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RADIOBTNrabbit.setText("RABBIT");
        RADIOBTNrabbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RADIOBTNrabbitActionPerformed(evt);
            }
        });

        buttonGroup1.add(RADIOBTNpig);
        RADIOBTNpig.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RADIOBTNpig.setText("PIG");
        RADIOBTNpig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RADIOBTNpigActionPerformed(evt);
            }
        });

        RADIOBTNTITLE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RADIOBTNTITLE.setText("SELECT ANIMAL");

        picdisplay.setLabelFor(picdisplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RADIOBTNbird, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(16, 16, 16))
                            .addComponent(RADIOBTNcat)
                            .addComponent(RADIOBTNdog)
                            .addComponent(RADIOBTNrabbit)
                            .addComponent(RADIOBTNpig))
                        .addGap(89, 89, 89))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RADIOBTNTITLE, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(picdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(RADIOBTNTITLE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(RADIOBTNbird)
                        .addGap(34, 34, 34)
                        .addComponent(RADIOBTNcat)
                        .addGap(34, 34, 34)
                        .addComponent(RADIOBTNdog)
                        .addGap(34, 34, 34)
                        .addComponent(RADIOBTNrabbit)
                        .addGap(34, 34, 34)
                        .addComponent(RADIOBTNpig))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(picdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void RADIOBTNrabbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RADIOBTNrabbitActionPerformed
       ImageIcon icon= new ImageIcon(getClass().getResource("/images/rabbit.jpg"));
       picdisplay.setIcon(icon);
    }//GEN-LAST:event_RADIOBTNrabbitActionPerformed

    private void RADIOBTNbirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RADIOBTNbirdActionPerformed
       ImageIcon icon= new ImageIcon(getClass().getResource("/images/bird.jpg"));
       picdisplay.setIcon(icon);
    }//GEN-LAST:event_RADIOBTNbirdActionPerformed

    private void RADIOBTNcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RADIOBTNcatActionPerformed
         ImageIcon icon= new ImageIcon(getClass().getResource("/images/cat.jpg"));
       picdisplay.setIcon(icon);
    }//GEN-LAST:event_RADIOBTNcatActionPerformed

    private void RADIOBTNdogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RADIOBTNdogActionPerformed
       ImageIcon icon= new ImageIcon(getClass().getResource("/images/dog.jpg"));
       picdisplay.setIcon(icon);
        
    }//GEN-LAST:event_RADIOBTNdogActionPerformed

    private void RADIOBTNpigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RADIOBTNpigActionPerformed
       ImageIcon icon= new ImageIcon(getClass().getResource("/images/pig.jpg"));
         picdisplay.setIcon(icon);
    }//GEN-LAST:event_RADIOBTNpigActionPerformed
       
               
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RADIOBTN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RADIOBTN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RADIOBTN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RADIOBTN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RADIOBTN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RADIOBTNTITLE;
    private javax.swing.JRadioButton RADIOBTNbird;
    private javax.swing.JRadioButton RADIOBTNcat;
    private javax.swing.JRadioButton RADIOBTNdog;
    private javax.swing.JRadioButton RADIOBTNpig;
    private javax.swing.JRadioButton RADIOBTNrabbit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel picdisplay;
    // End of variables declaration//GEN-END:variables
}
